from glob import glob
from pathlib import Path
import os

env = SConscript("godot-cpp/SConstruct")

env.Append(CPPPATH=[
    "src/CompoundCloudPlane++",  # Root directory
    "src/CompoundCloudPlane++/json",  # Specifically add the json directory
])

print("Include paths:", env['CPPPATH'])

source_files = []
for path in Path("src/CompoundCloudPlane++").rglob("*.cpp"):
    if "bin" not in path.parts:
        source_files.append(str(path))

(extension_path,) = glob("src/*.gdextension")

addon_path = Path(extension_path).parent

project_name = Path(extension_path).stem

debug_or_release = "release" if env["target"] == "template_release" else "debug"
if env["platform"] == "macos":
    library = env.SharedLibrary(
        "{0}/bin/lib{1}.{2}.{3}.framework/{1}.{2}.{3}".format(
            addon_path,
            project_name,
            env["platform"],
            debug_or_release,
        ),
        source=source_files,
    )
else:
    library = env.SharedLibrary(
        "{}/bin/lib{}.{}.{}.{}{}".format(
            addon_path,
            project_name,
            env["platform"],
            debug_or_release,
            env["arch"],
            env["SHLIBSUFFIX"],
        ),
        source=source_files,
    )

Default(library)
